# fly.toml app configuration file generated for my-yattee-server on 2026-02-16T10:38:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-yattee-server'
primary_region = 'nrt'

[build]

[[mounts]]
  source = "data"
  destination = "/app/data"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "5GB"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 8085
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
